name: Fork
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fork:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6

      - name: Clean working tree
        run: |
          shopt -s extglob
          rm -rf !( .git | .github )

      - name: Fetch upstream
        run: |
          git remote add upstream https://go.googlesource.com/sys || true
          git fetch upstream
          git reset --hard upstream/master
          git checkout origin/main .github/

      - name: Modify
        working-directory: .github/workflows
        run: go run main.go ../../unix

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Panic at all syscalls in unix"
          git tag v0.0.1

      - name: Push
        run: |
          git push --force
          git push --force origin v0.0.1
